### ISSUE TITLE
assert!(!self.lock_flag(), "Recursion detected") panic

### ISSUE THREAD

**Issue by jturcotte** [sixtyfpsui/sixtyfps#140]
This triggers `assert!(!self.lock_flag(), "Recursion detected")` in `PropertyHandle::remove_binding` when using 0.0.4 and current master:

```css
HelloWorld := Window {
    HorizontalLayout {
        VerticalLayout {
            HorizontalLayout {
                height: 50%;
                Rectangle {}
            }
        }
    }
}
```
