### ISSUE TITLE
Vertical layout width is computed incorrectly (min vs max)

### ISSUE THREAD

**Issue by matklad** [sixtyfpsui/sixtyfps#160]
https://sixtyfps.io/editor/?snippet=import+%7B+SpinBox,+Button,+CheckBox,+Slider,+GroupBox+%7D+from+%22sixtyfps_widgets.60%22;export+Demo+:=+Window+%7B++++width:++600px;+++//+Width+in+logical+pixels.+All+'px'+units+are+automatically+scaled+with+screen+resolution.++++height:+300px;++++property%3C%5Bint%5D%3E+xs:+%5B200,100,300%5D;++++HorizontalLayout+%7B++++++++alignment:+center;++++++++Rectangle+%7B+background:+blue;+width:+10px;+%7D++++++++VerticalLayout+%7B++++++++++++for+x%5Bi%5D+in+xs:+Rectangle+%7B++++++++++++++++height:+10px;++++++++++++++++width:+1px+*+x;++++++++++++++++color:+red;++++++++++++%7D++++++++%7D++++++++Rectangle+%7B+background:+blue;+width:+10px;+%7D++++%7D%7D

![image](https://user-images.githubusercontent.com/1711539/107067114-e3b3fb00-67ef-11eb-91ec-cc2f674bd892.png)

**Comment by ogoffart** [comment]
It looks like the box layout does not handle correctly this case indeed.

---

Code for the link pasted there for convenience:  (somehow the link stripped the new lines)
```css
export Demo := Window {   
    width:  600px;  
    height: 300px;    
    property<[int]> xs: [200,100,300];   
    HorizontalLayout {    
        alignment: center;   
        Rectangle { background: blue; width: 10px; }  
        VerticalLayout {    
            for x[i] in xs: Rectangle { 
                height: 10px;  
                width: 1px * x;     
                color: red;    
            }      
        }      
        Rectangle { background: blue; width: 10px; }  
    }
}
```
