### ISSUE TITLE
Layout inside `if` are not automatically computed

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#167]
The following example is not working (for example with the interpreter)

```css
export Demo := Window {
    width:  300px; 
    height: 300px;
    if (true) : Rectangle {
        color: black;
        VerticalLayout {
            Rectangle { background: blue; }
            Rectangle { background: red; }
        }
    }
}
```

Only resizing the window will cause the layout to be re-layouted.

Workaround:  put the if within a layout

```css
export Demo := Window {
    width:  300px; 
    height: 300px;
  VerticalLayout { // added
    if (true) : Rectangle {
        color: black;
        VerticalLayout {
            Rectangle { background: blue; }
            Rectangle { background: red; }
        }
    }
 }
}
```
