### ISSUE TITLE
Sizing of Image in Layout

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#168]
Consider

```css
VerticalLayout {
      Rectangle {
         background: blue;
      }
      Image {
         source: @image-url("...");
         //image-fit: contain;
         //vertical-stretch: 1;
      }
}
```

The question is how do we share the space between the Rectangle and the Image, given some original source size of the image.

Some option include:

 1. The image max and min size is the one from the source size, and so the image has a fixed size
 2. The Image is resized exactly like a Rectangle, the default `stretch` would also be `1` like the rectangle
 3. We introduce a concept of preferred size and the default stretch is `0`
 4. We make it depends on the `image-fit` property.  If the image-fit property is `none` then we use solution # 1, otherwise solution # 2
