### ISSUE TITLE
How to use the image in memory

### ISSUE THREAD

**Issue by LLouice** [sixtyfpsui/sixtyfps#186]
I know there is 
```
Image {
            source: @image-url("https://sixtyfps.io/resources/logo_scaled.png");
}
```

 that can use image file.But I don't find the way to use the image in memory

**Comment by ogoffart** [comment]
Hi @LLouice 

There is no way with the public API to do that.

Using the Private API, currently, using [Resource::EmbeddedRgbaImage](https://docs.rs/sixtyfps-corelib/0.0.4/sixtyfps_corelib/enum.Resource.html#variant.EmbeddedRgbaImage)
So you will have to write something like

```css
MyApp := {
   property <resource> img;
   Image {
      source: root.img;
   }
}
```

then you should be able to set programatically the img property to a Resource::EmbeddedRgbaImage

We plan to expose such capability in the public API in the future.
