### ISSUE TITLE
Access the size of an `image` resource

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#208]
Would be nice to be able to access the size directly on a `property<image>`.
Also we need to know if the image is set to something or not.

```css
property <image> source;
if (source.width > 0) :Image {
   source: root.source;
}
```

Proposal:
 - add `width` and `height`  pseudo-field to the `image` type.
 - Should we add `is_empty` or `is_valid` or `is_null` ?
 - Should they be function-like?  (ie;  `source.width()` or just `source.width`)
